-- AlterTable
ALTER TABLE "User" ADD COLUMN     "avgTip" DECIMAL(65,30) NOT NULL DEFAULT 20.21,
ADD COLUMN     "credits" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "rating" DECIMAL(65,30) NOT NULL DEFAULT 5.21;
